// FTTB (Ethernet): в одном месте и конфиг, и диагностика по каждому устройству.
// Добавление нового устройства: допишите новый ключ в fttbDevices.

window.fttbDevices = {
  eltex_2428: {
    label: "Eltex 24xx",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `interface ${portType} ${port}`,
        `  switchport mode access`,
        `  switchport access vlan ${accessVlan}`,
        `  description "${desc}"`,
        `  storm-control broadcast level 10`,
        `  spanning-tree portfast`,
        `  no shutdown`,
        `  exit`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `interface ${portType} ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `interface ${portType} ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk native vlan ${nativeVlan}`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `configure terminal`,
        `snooping multicast-forwarding-mode ip`,
        `map protocol other 88:63 Enet-v2 protocols-group 1`,
        `map protocol other 88:64 Enet-v2 protocols-group 1`,
        `interface GigabitEthernet ${port}`,
        `description ${desc}`,
        `switchport mode general`,
        `switchport general allowed vlan add ${tr069Vlan},${pppoeVlan} untagged`,
        `switchport general allowed vlan add ${taggedVlan}`,
        `switchport general pvid ${tr069Vlan}`,
        `switchport map protocols-group 1 vlan ${pppoeVlan}`,
        `dcs agent-circuit-identifier "%h eth %u/%s/%i:%v"`,
        `dcs remote-agent-identifier "%M"`,
        `no shutdown`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
        `y`,
      ],
    },
    diagnostics: {
      "Физика порта": [
        { command: `show interface {portType} {port}`, description: "Общая информация о порте" },
        { command: `show interface {portType} {port} status`, description: "Up/down, скорость, дуплекс" },
        { command: `show interface {portType} {port} counters`, description: "Счетчики/ошибки на порту" },
        { command: `show cable-diagnostics tdr interface {portType} {port}`, description: "TDR-тест кабеля" },
      ],
      "Конфигурация": [
        { command: `show running-config interface {portType} {port}`, description: "Текущая конфигурация порта" },
        { command: `show vlan id {vlan}`, description: "Информация по VLAN" },
        { command: `show vlan brief`, description: "Список VLAN" },
      ],
      "MAC-таблица": [
        { command: `show mac address-table interface {portType} {port}`, description: "MAC на конкретном порту" },
        { command: `show mac address-table`, description: "Глобальная MAC-таблица" },
        { command: `show mac address-table vlan {vlan}`, description: "MAC внутри VLAN" },
      ],
      "STP/Безопасность": [
        { command: `show spanning-tree interface {portType} {port}`, description: "STP состояние на порту" },
        { command: `show port-security interface {portType} {port}`, description: "Port-security на порту" },
      ],
    },
  },

  eltex: {
    label: "Eltex (общий)",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `interface ${portType} ${port}`,
        `  switchport mode access`,
        `  switchport access vlan ${accessVlan}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `interface ${portType} ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `interface ${portType} ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk native vlan ${nativeVlan}`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `configure terminal`,
        `vlan database`,
        `map protocol 8863 ethernet protocols-group 1`,
        `map protocol 8864 ethernet protocols-group 1`,
        `exit`,
        `interface GigabitEthernet ${port}`,
        `description ${desc}`,
        `switchport mode general`,
        `switchport general pvid ${tr069Vlan}`,
        `switchport general allowed vlan add ${tr069Vlan},${pppoeVlan} untagged`,
        `switchport general allowed vlan add ${taggedVlan} tagged`,
        `switchport general map protocols-group 1 vlan ${pppoeVlan}`,
        `no shutdown`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
        `y`,
      ],
    },
    diagnostics: {
      "Физика порта": [
        { command: `show interface {portType} {port}`, description: "Информация о порте" },
        { command: `show interface {portType} {port} status`, description: "Статус порта" },
        { command: `show interface {portType} {port} counters`, description: "Счетчики порта" },
      ],
      "Конфигурация": [
        { command: `show running-config interface {portType} {port}`, description: "Конфигурация порта" },
        { command: `show vlan`, description: "Список VLAN" },
      ],
      "MAC-таблица": [
        { command: `show mac address-table interface {portType} {port}`, description: "MAC-адреса на порту" },
        { command: `show mac address-table`, description: "Вся MAC-таблица" },
      ],
    },
  },

  edgecore_es3526_xa: {
    label: "Edge Core ES3526 XA",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `vlan ${accessVlan}`,
        `interface ${portType} ${port}`,
        `  switchport mode access`,
        `  switchport access vlan ${accessVlan}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `interface ${portType} ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `interface ${portType} ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk native vlan ${nativeVlan}`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `interface ${portType} ${port}`,
        `  description "${desc}"`,
        `  switchport mode trunk`,
        `  switchport trunk allowed vlan add ${tr069Vlan},${pppoeVlan},${taggedVlan}`,
        `  no shutdown`,
        `  exit`,
      ],
    },
    diagnostics: {
      "Физика порта": [
        { command: `show interface {portType} {port}`, description: "Информация о порте" },
        { command: `show interface {portType} {port} counters`, description: "Счетчики порта" },
      ],
      "Конфигурация": [
        { command: `show running-config interface {portType} {port}`, description: "Конфигурация порта" },
        { command: `show vlan`, description: "Список VLAN" },
      ],
      "MAC-таблица": [
        { command: `show mac-addr-table interface {portType} {port}`, description: "MAC-адреса на порту" },
        { command: `show mac-addr-table`, description: "Вся MAC-таблица" },
      ],
      "Безопасность": [
        { command: `show port security {port}`, description: "Настройки безопасности порта" },
      ],
    },
  },

  edgecore_es3526_m: {
    label: "Edge Core ES3526 M",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `vlan database`,
        `  vlan ${accessVlan}`,
        `  exit`,
        `interface ethernet ${port}`,
        `  switchport mode access`,
        `  switchport access vlan ${accessVlan}`,
        `  description "${desc}"`,
        `  exit`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `interface ethernet ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  exit`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `interface ethernet ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk native vlan ${nativeVlan}`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  exit`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `interface ethernet ${port}`,
        `  description "${desc}"`,
        `  switchport mode trunk`,
        `  switchport trunk allowed vlan add ${tr069Vlan},${pppoeVlan},${taggedVlan}`,
        `  exit`,
      ],
    },
    diagnostics: {
      "Физика порта": [
        { command: `show interface ethernet {port}`, description: "Информация о порте" },
        { command: `show interface counters ethernet {port}`, description: "Счетчики порта" },
      ],
      "Конфигурация": [
        { command: `show running-config`, description: "Текущая конфигурация" },
      ],
      "MAC-таблица": [
        { command: `show mac-address-table ethernet {port}`, description: "MAC-адреса на порту" },
      ],
    },
  },

  alsitek: {
    label: "Alsitek",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `interface ethernet ${port}`,
        `  switchport mode access`,
        `  switchport access vlan ${accessVlan}`,
        `  description "${desc}"`,
        `  storm-control broadcast 100`,
        `  no shutdown`,
        `  exit`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `interface ethernet ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `interface ethernet ${port}`,
        `  switchport mode trunk`,
        `  switchport trunk native vlan ${nativeVlan}`,
        `  switchport trunk allowed vlan ${allowedVlans}`,
        `  description "${desc}"`,
        `  no shutdown`,
        `  exit`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `interface ethernet ${port}`,
        `  description "${desc}"`,
        `  switchport mode trunk`,
        `  switchport trunk allowed vlan add ${tr069Vlan},${pppoeVlan},${taggedVlan}`,
        `  no shutdown`,
        `  exit`,
      ],
    },
    diagnostics: {
      "Физика порта": [
        { command: `show interface ethernet {port}`, description: "Информация о порте" },
        { command: `show interface ethernet {port} statistics`, description: "Статистика порта" },
        { command: `show cable-diagnostics ethernet {port}`, description: "Диагностика кабеля" },
      ],
      "Конфигурация": [
        { command: `show running-config interface ethernet {port}`, description: "Конфигурация порта" },
      ],
      "MAC-таблица": [
        { command: `show mac-address-table interface ethernet {port}`, description: "MAC-адреса на порту" },
      ],
    },
  },

  alsitek_fttb: {
    label: "Alsitek FTTB",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `configure`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport trunk allowed vlan remove all`,
        `switchport mode access`,
        `switchport access vlan ${accessVlan}`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `configure`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport mode trunk`,
        `switchport trunk allowed vlan add ${allowedVlans}`,
        `switchport trunk native vlan 1`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `configure`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport mode trunk`,
        `switchport trunk allowed vlan add ${allowedVlans}`,
        `switchport trunk allowed vlan remove ${nativeVlan}`,
        `switchport trunk native vlan ${nativeVlan}`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `configure`,
        `vlan database`,
        `map protocol 8863 ethernet protocols-group 1`,
        `map protocol 8864 ethernet protocols-group 1`,
        `exit`,
        `interface ethernet ${port}`,
        `no shutdown`,
        `description ${desc}`,
        `switchport mode general`,
        `switchport general pvid ${tr069Vlan}`,
        `switchport general allowed vlan add ${tr069Vlan},${pppoeVlan} untagged`,
        `switchport general allowed vlan add ${taggedVlan} tagged`,
        `switchport general map protocols-group 1 vlan ${pppoeVlan}`,
        `no shutdown`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
      ],
    },
    diagnostics: {
      "Работа с портом": [
        { command: `show interfaces status`, description: "Список портов" },
        { command: `show interfaces status ethernet {port}`, description: "Статус порта" },
        { command: `show interfaces counters ethernet {port}`, description: "Ошибки на порту" },
      ],
      "Работа с конфигом": [
        { command: `show interfaces switchport ethernet {port}`, description: "Конфиг порта" },
      ],
      "Работа с МАС": [
        { command: `show bridge address-table`, description: "MAC-таблица" },
        { command: `show bridge address-table ethernet {port}`, description: "MAC на порту" },
      ],
    },
  },

  edgecore_es3528_m: {
    label: "Edge Core ES3528 M",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `configure`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport mode access`,
        `switchport access vlan ${accessVlan}`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
        `startup1.cfg`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `configure`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport mode trunk`,
        `switchport allowed vlan add ${allowedVlans} tagged`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
        `startup1.cfg`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `configure`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport mode hybrid`,
        `switchport allowed vlan add ${allowedVlans} tagged`,
        `switchport allowed vlan add ${nativeVlan} untagged`,
        `switchport native vlan ${nativeVlan}`,
        `switchport allowed vlan remove 1`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
        `startup1.cfg`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `configure`,
        `protocol-vlan protocol-group 1 add frame-type ethernet protocol-type pppoe`,
        `no protocol-vlan protocol-group 1 vlan`,
        `protocol-vlan protocol-group 1 vlan ${pppoeVlan}`,
        `interface ethernet ${port}`,
        `description "${desc}"`,
        `switchport mode hybrid`,
        `switchport allowed vlan add ${tr069Vlan},${pppoeVlan} untagged`,
        `switchport allowed vlan add ${taggedVlan} tagged`,
        `switchport native vlan ${tr069Vlan}`,
        `switchport allowed vlan remove 1`,
        `exit`,
        `exit`,
        `copy running-config startup-config`,
        `y`,
      ],
    },
    diagnostics: {
      "Работа с портом": [
        { command: `show interfaces brief`, description: "Краткий статус портов" },
        { command: `show interfaces status ethernet {port}`, description: "Статус порта" },
        { command: `show interfaces counters ethernet {port}`, description: "Ошибки на порту" },
      ],
      "Работа с VLAN": [
        { command: `show vlan`, description: "Список VLAN" },
      ],
      "Работа с MAC": [
        { command: `show mac-address-table interface ethernet {port}`, description: "MAC на порту" },
      ],
    },
  },

  dlink_des3200: {
    label: "D-Link",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `config ports ${port} description ${desc}`,
        `config vlan vlanid ${accessVlan} add untagged ${port}`,
        `config ports ${port} state enable`,
        `save all`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `config ports ${port} description ${desc}`,
        `config vlan vlanid ${allowedVlans} add tagged ${port}`,
        `config ports ${port} state enable`,
        `save all`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `config ports ${port} description ${desc}`,
        `config vlan vlanid ${nativeVlan} add untagged ${port}`,
        `config vlan vlanid ${allowedVlans} add tagged ${port}`,
        `config ports ${port} state enable`,
        `save all`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `config ports ${port} description "${desc}"`,
        `config vlan ${tr069Vlan} add untagged ${port}`,
        `config vlan ${pppoeVlan} add untagged ${port}`,
        `config vlan ${taggedVlan} add tagged ${port}`,
        `config gvrp ${tr069Vlan} pvid ${tr069Vlan}`,
        `config port dot1v ports ${port} add protocol_group group_id 1 vlan ${pppoeVlan}`,
        `config port dot1v ports ${port} add protocol_group group_id 2 vlan ${pppoeVlan}`,
      ],
    },
    diagnostics: {
      "Системная информация": [
        { command: `show switch`, description: "Информация о свитче" },
      ],
      "Multicast": [
        { command: `show address_binding dhcp_snoop binding_entry`, description: "DHCP Snooping записи" },
        { command: `show address_binding ip_mac all`, description: "IP/MAC записи" },
      ],
      "Статус портов": [
        { command: `show ports`, description: "Список портов" },
        { command: `show ports {port}`, description: "Информация о порту" },
        { command: `show ports description`, description: "Описания портов" },
      ],
      "Ошибки на порту": [
        { command: `show error ports {port}`, description: "Ошибки на порту" },
      ],
      "Конфигурация порта": [
        { command: `show ports {port} configuration vlan`, description: "VLAN-конфигурация порта" },
        { command: `show vlan ports {port}`, description: "VLAN на порту" },
        { command: `show port dot1v ports {port}`, description: "Dot1v на порту" },
      ],
      "Диагностика кабеля": [
        { command: `cable_diag ports {port}`, description: "Диагностика кабеля (cable_diag)" },
        { command: `cable diagnostic port {port}`, description: "Диагностика кабеля (cable diagnostic)" },
      ],
      "Просмотр MAC-адресов": [
        { command: `show fdb`, description: "Все MAC-адреса" },
        { command: `show fdb vlanid {vlan}`, description: "MAC-адреса во VLAN" },
        { command: `show fdb port {port}`, description: "MAC-адреса на порту" },
      ],
      "Просмотр логов": [
        { command: `show log`, description: "Логи устройства" },
      ],
      "Перезапуск порта": [
        { command: `config ports {port} state disable
config ports {port} state enable`, description: "Перезапуск порта" },
      ],
      "Безопасность": [
        { command: `show port_security`, description: "Статус port-security" },
        { command: `config port_security ports {port} admin_state disable max_learning_addr 0 lock_address_mode DeleteOnTimeout`, description: "Сброс port-security на порту" },
      ],
      "Счетчики": [
        { command: `clear counters ports {port}`, description: "Сброс счетчиков на порту" },
      ],
    },
  },

  huawei_switch: {
    label: "Huawei (?????)",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `system-view`,
        `interface GigabitEthernet ${port}`,
        `description "${desc}"`,
        `port link-type access`,
        `port default vlan ${accessVlan}`,
        `quit`,
        `quit`,
        `save all`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `system-view`,
        `interface GigabitEthernet${port}`,
        `description ${desc}`,
        `port link-type trunk`,
        `port trunk allow-pass vlan ${allowedVlans}`,
        `quit`,
        `quit`,
        `save all`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `system-view`,
        `interface GigabitEthernet0/0/${port}`,
        `description ${desc}`,
        `port link-type hybrid`,
        `port hybrid pvid vlan ${nativeVlan}`,
        `port hybrid untagged vlan ${nativeVlan}`,
        `port hybrid tagged vlan ${allowedVlans}`,
        `quit`,
        `quit`,
        `save all`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `system-view`,
        `vlan ${tr069Vlan}`,
        `protocol-vlan ipv4`,
        `quit`,
        `vlan ${pppoeVlan}`,
        `protocol-vlan mode ethernetii-etype 8863`,
        `protocol-vlan mode ethernetii-etype 8864`,
        `quit`,
        `interface GigabitEthernet 0/0/${port}`,
        `undo shutdown`,
        `description "${desc}"`,
        `port hybrid pvid vlan ${tr069Vlan}`,
        `undo port hybrid vlan 1`,
        `port hybrid untagged vlan ${tr069Vlan} ${pppoeVlan}`,
        `protocol-vlan vlan ${tr069Vlan} ${pppoeVlan} all priority 0`,
        `port hybrid tagged vlan ${taggedVlan}`,
        `return`,
        `save`,
        `y`,
      ],
    },
    diagnostics: {
      "Версия устройства": [
        { command: `display version`, description: "Версия ПО" },
      ],
      "Статус портов": [
        { command: `display interface brief`, description: "Краткий статус интерфейсов" },
        { command: `display interface description`, description: "Описание интерфейсов" },
        { command: `display interface GigabitEthernet{port}`, description: "Информация по порту" },
      ],
      "Конфигурация портов": [
        { command: `display current-configuration`, description: "Текущая конфигурация" },
        { command: `display current-configuration interface GigabitEthernet{port}`, description: "Конфигурация порта" },
        { command: `display protocol-vlan interface GigabitEthernet{port}`, description: "Protocol VLAN на порту" },
      ],
      "Просмотр MAC-адресов": [
        { command: `display mac-address dynamic`, description: "Все MAC-адреса" },
        { command: `display mac-address dynamic GigabitEthernet{port}`, description: "MAC на порту" },
        { command: `display mac-address dynamic vlan {vlan}`, description: "MAC во VLAN" },
      ],
      "IGMP Snooping": [
        { command: `display igmp-snooping port-info | include Eth{port}`, description: "IGMP Snooping по порту" },
      ],
      "Просмотр логов": [
        { command: `display logbuffer`, description: "Логи" },
      ],
      "Сохранение": [
        { command: `save`, description: "Сохранение конфигурации" },
      ],
      "Cable Diagnostic": [
        { command: `system-view
interface GigabitEthernet{port}
virtual-cable-test`, description: "Диагностика кабеля" },
      ],
    },
  },

  huawei_3328: {
    label: "Huawei 3328",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `system-view`,
        `interface GigabitEthernet0/0/${port}`,
        `description ${desc}`,
        `port link-type access`,
        `port default vlan ${accessVlan}`,
        `restart`,
        `quit`,
        `quit`,
        `save all`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `system-view`,
        `interface GigabitEthernet0/0/${port}`,
        `description ${desc}`,
        `port link-type trunk`,
        `port trunk allow-pass vlan ${allowedVlans}`,
        `restart`,
        `quit`,
        `quit`,
        `save all`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `system-view`,
        `interface GigabitEthernet0/0/${port}`,
        `description ${desc}`,
        `port link-type hybrid`,
        `port hybrid pvid vlan ${nativeVlan}`,
        `port hybrid untagged vlan ${nativeVlan}`,
        `port hybrid tagged vlan ${allowedVlans}`,
        `restart`,
        `quit`,
        `quit`,
        `save all`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `system-view`,
        `vlan ${tr069Vlan}`,
        `protocol-vlan ipv4`,
        `quit`,
        `vlan ${pppoeVlan}`,
        `protocol-vlan mode ethernetii-etype 8863`,
        `protocol-vlan mode ethernetii-etype 8864`,
        `quit`,
        `interface GigabitEthernet 0/0/${port}`,
        `undo shutdown`,
        `description "${desc}"`,
        `dhcp snooping enable`,
        `dhcp option82 insert enable`,
        `port hybrid pvid vlan ${tr069Vlan}`,
        `undo port hybrid vlan 1`,
        `port hybrid untagged vlan ${tr069Vlan} ${pppoeVlan}`,
        `protocol-vlan vlan ${tr069Vlan} ${pppoeVlan} all priority 0`,
        `port hybrid tagged vlan ${taggedVlan}`,
        `return`,
        `save`,
        `y`,
      ],
    },
    diagnostics: {
      "Версия устройства": [
        { command: `display version`, description: "Версия ПО" },
      ],
      "Статус портов": [
        { command: `display interface brief`, description: "Краткий статус интерфейсов" },
        { command: `display interface description`, description: "Описание интерфейсов" },
        { command: `display interface GigabitEthernet{port}`, description: "Информация по порту" },
      ],
      "Конфигурация портов": [
        { command: `display current-configuration`, description: "Текущая конфигурация" },
        { command: `display current-configuration interface GigabitEthernet{port}`, description: "Конфигурация порта" },
        { command: `display protocol-vlan interface GigabitEthernet{port}`, description: "Protocol VLAN на порту" },
      ],
      "Просмотр MAC-адресов": [
        { command: `display mac-address dynamic`, description: "Все MAC-адреса" },
        { command: `display mac-address dynamic GigabitEthernet{port}`, description: "MAC на порту" },
        { command: `display mac-address dynamic vlan {vlan}`, description: "MAC во VLAN" },
      ],
      "IGMP Snooping": [
        { command: `display igmp-snooping port-info | include Eth{port}`, description: "IGMP Snooping по порту" },
      ],
      "Просмотр логов": [
        { command: `display logbuffer`, description: "Логи" },
      ],
      "Сохранение": [
        { command: `save`, description: "Сохранение конфигурации" },
      ],
      "Cable Diagnostic": [
        { command: `system-view
interface GigabitEthernet{port}
virtual-cable-test`, description: "Диагностика кабеля" },
      ],
    },
  },

  si3000: {
    label: "Si3000",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `configure`,
        `interface ${port}`,
        `description ${desc}`,
        `vlan participation include ${accessVlan}`,
        `no vlan tagging ${accessVlan}`,
        `vlan pvid ${accessVlan}`,
        `no shutdown`,
        `exit`,
        `exit`,
        `write memory`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `configure`,
        `interface ${port}`,
        `description ${desc}`,
        `vlan participation include ${allowedVlans}`,
        `vlan tagging ${allowedVlans}`,
        `no shutdown`,
        `exit`,
        `exit`,
        `write memory`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `configure`,
        `interface ${port}`,
        `description ${desc}`,
        `vlan participation include ${allowedVlans}`,
        `vlan tagging ${allowedVlans}`,
        `vlan pvid ${nativeVlan}`,
        `no shutdown`,
        `exit`,
        `exit`,
        `write memory`,
      ],
    },
    diagnostics: {
      "Работа с портом": [
        { command: `show port all`, description: "Список портов" },
        { command: `show port description {port}`, description: "Описание порта" },
        { command: `show interface {port}`, description: "Информация о порту" },
      ],
    },
  },

  snr: {
    label: "SNR FTTB",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `configure terminal`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `no switchport trunk native vlan`,
        `no switchport trunk allowed vlan`,
        `switchport mode access`,
        `switchport access vlan ${accessVlan}`,
        `no shutdown`,
        `end`,
        `write`,
        `y`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `configure terminal`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport mode trunk`,
        `switchport trunk allowed vlan add ${allowedVlans}`,
        `no shutdown`,
        `end`,
        `write`,
        `y`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `configure terminal`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport mode trunk`,
        `switchport trunk allowed vlan add ${allowedVlans}`,
        `switchport trunk native vlan ${nativeVlan}`,
        `no shutdown`,
        `end`,
        `write`,
        `y`,
      ],
      dot1v: ({ portType, port, tr069Vlan, pppoeVlan, taggedVlan, desc }) => [
        `configure terminal`,
        `protocol-vlan etype 34915 vlan ${pppoeVlan} priority 0`,
        `protocol-vlan etype 34916 vlan ${pppoeVlan} priority 0`,
        `interface ethernet ${port}`,
        `description ${desc}`,
        `switchport mode hybrid`,
        `switchport hybrid allowed vlan add ${tr069Vlan},${pppoeVlan} untag`,
        `switchport hybrid native vlan ${tr069Vlan}`,
        `switchport hybrid allowed vlan add ${taggedVlan} tag`,
        `no shutdown`,
        `end`,
        `write`,
        `y`,
      ],
    },
    diagnostics: {
      "Работа с портом": [
        { command: `show interface ethernet status`, description: "Состояние портов" },
        { command: `show interface ethernet {port}`, description: "Информация о порту" },
      ],
    },
  },

  zyxel_fttb: {
    label: "Zyxel FTTB",
    modes: {
      access: ({ portType, port, accessVlan, desc }) => [
        `configure`,
        `vlan ${accessVlan}`,
        `fixed ${port}`,
        `untagged ${port}`,
        `exit`,
        `interface port-channel ${port}`,
        `name ${desc}`,
        `no vlan-trunking`,
        `pvid ${accessVlan}`,
        `exit`,
        `exit`,
        `write memory`,
      ],
      trunk: ({ portType, port, allowedVlans, desc }) => [
        `configure`,
        `vlan ${allowedVlans}`,
        `fixed ${port}`,
        `no untagged ${port}`,
        `exit`,
        `interface port-channel ${port}`,
        `name ${desc}`,
        `exit`,
        `exit`,
        `write memory`,
      ],
      trunk_native: ({ portType, port, allowedVlans, nativeVlan, desc }) => [
        `configure`,
        `vlan ${allowedVlans}`,
        `fixed ${port}`,
        `no untagged ${port}`,
        `exit`,
        `vlan ${nativeVlan}`,
        `fixed ${port}`,
        `untagged ${port}`,
        `exit`,
        `interface port-channel ${port}`,
        `name ${desc}`,
        `no vlan-trunking`,
        `pvid ${nativeVlan}`,
        `exit`,
        `exit`,
        `write memory`,
      ],
    },
    diagnostics: {
      "Работа с портом": [
        { command: `show interfaces status`, description: "Статус портов" },
        { command: `show interfaces {port}`, description: "Информация о порту" },
      ],
      "Работа с VLAN": [
        { command: `show vlan`, description: "Список VLAN" },
      ],
    },
  },
  sib_templates: {
    label: "Сибирь: шаблоны (из файла)",
    modes: {},
    diagnostics: {},
  },
};
