// GPON: в одном месте и конфиг, и диагностика по каждому устройству.

window.gponDevices = {
  huawei: {
    label: "Huawei OLT",
    services: {},
    diagnostics: {
      "Информация об ONT": [
        { command: `config\ninterface gpon {frameSlot}`, description: "Вход в интерфейс GPON" },
        { command: `display ont info {ponPort} {ontIdx}`, description: "Общая информация/статус ONT" },
        { command: `display ont version {ponPort} {ontIdx}`, description: "Версия прошивки ONT" },
        { command: `display ont register-info {ponPort} {ontIdx}`, description: "Регистрация ONT" },
        { command: `display ont state {ponPort} {ontIdx}`, description: "Текущее состояние ONT" },
      ],
      "Оптика": [
        { command: `config\ninterface gpon {frameSlot}`, description: "Вход в интерфейс GPON" },
        { command: `display ont optical-info {ponPort} {ontIdx}`, description: "Rx/Tx, температура, напряжение" },
        { command: `display ont optical-alarm {ponPort} {ontIdx}`, description: "Алармы по оптике" },
      ],
      "Конфигурация": [
        { command: `config\ninterface gpon {frameSlot}`, description: "Вход в интерфейс GPON" },
        { command: `display ont wan-info {ponPort} {ontIdx}`, description: "WAN настройки ONT" },
        { command: `display ont port state {ponPort} {ontIdx} eth-port all`, description: "Состояние всех Ethernet портов ONT" },
        { command: `display service-port port {gponPort} ont {ontIdx}`, description: "Сервис-порты ONT" },
        { command: `display ont config {ponPort} {ontIdx}`, description: "Текущая конфигурация ONT" },
      ],
      "MAC-таблица": [
        { command: `display mac-address port {gponPort} ont {ontIdx}`, description: "MAC-адреса на ONT" },
        { command: `display mac-address all`, description: "Глобальная MAC-таблица" },
      ],
      "Статистика": [
        { command: `config\ninterface gpon {frameSlot}`, description: "Вход в интерфейс GPON" },
        { command: `display ont statistics {ponPort} {ontIdx}`, description: "Статистика ONT (пакеты, ошибки)" },
        { command: `display ont port statistics {ponPort} {ontIdx} eth-port all`, description: "Статистика Ethernet портов" },
      ],
      "Алармы/логи": [
        { command: `config\ninterface gpon {frameSlot}`, description: "Вход в интерфейс GPON" },
        { command: `display ont alarm-state {ponPort} {ontIdx}`, description: "Алармы на ONT" },
        { command: `display alarm active all`, description: "Активные алармы" },
        { command: `display logbuffer | include {ontId}`, description: "Логи с упоминанием ONT" },
      ],
    },
  },

  electra: {
    label: "Electra OLT",
    services: {},
    diagnostics: {
      "Диагностика общая": [
        { command: `show ont autofind all`, description: "Просмотр не активированных ONT" },
        { command: `show current-config section ont {frameSlot} {ponPort} {ontIdx}`, description: "Просмотр конфигурации на ONT" },
        { command: `show ont-line-profile gpon all`, description: "Просмотр списка линейных профилей на OLT" },
        { command: `show ont-srv-profile gpon all`, description: "Просмотр списка сервис профилей на OLT" },
        { command: `show ont-tr069-profile all`, description: "Просмотр списка tr-069 профилей на OLT" },
        { command: `show multicast-vlan all`, description: "Диагностика Мультикаст" },
        { command: `show current-config include pon {gponPort} ont {ontIdx} no-auth max-program 32`, description: "Просмотр User-Index для мультикаст VLAN" },
        { command: `show ont info {frameSlot} {ponPort} all`, description: "Просмотр всех ONT ID на оптическом порту" },
        { command: `show mac-address port pon {gponPort} ont {ontIdx}`, description: "Просмотр MAC-адресов на ONT ID" },
        { command: `config\ninterface gpon {frameSlot}\nshow ont optical-info {ponPort} all`, description: "Просмотр мощности оптического сигнала всех ONT ID на оптическом порту" },
        { command: `show mac-address all include {mac}`, description: "Поиск порта и ONT ID по MAC-адресу" },
        { command: `show ont info by-sn {sn}`, description: "Поиск порта и ONT ID по SN" },
        { command: `show ont info {frameSlot} {ponPort} {ontIdx}`, description: "Просмотр состояния ONT ID" },
        { command: `config\ninterface gpon {frameSlot}\nshow ont optical-info {ponPort} {ontIdx}`, description: "Просмотр мощности оптического сигнала на ONT ID" },
      ],
      "Углубленная диагностика": [
        { command: `show vlan all`, description: "Просмотр всех VLAN" },
        { command: `show current-config`, description: "Просмотр глобальной конфигурации OLT" },
        { command: `show mac-address all`, description: "Просмотр всех MAC-адресов" },
        { command: `show mac-address vlan {svlan}`, description: "Просмотр MAC-адресов за VLAN" },
        { command: `show mac-address port pon {gponPort}`, description: "Просмотр MAC-адресов на оптическом порту" },
        { command: `show igmp group all`, description: "Просмотр мультикаст групп на OLT" },
        { command: `show igmp group port pon {gponPort}`, description: "Просмотр мулькаст групп на оптическом порту" },
        { command: `show ont info {frameSlot} {ponPort} all`, description: "Просмотр всех ONT ID на оптическом порту" },
        { command: `config\ninterface gpon {frameSlot}\nshow ont port state {ponPort} {ontIdx} eth all`, description: "Просмотр состояния LAN-портов на ONT" },
        { command: `show service-port gpon {frameSlot} port {ponPort}`, description: "Просмотр всех сервис портов на оптическом порту" },
        { command: `show ont version {frameSlot} {ponPort} {ontIdx}`, description: "Просмотр модели ONT терминала" },
        { command: `show ont info all online`, description: "Просмотр состояния всех ONLINE ONT ID на OLT" },
        { command: `config\ninterface gpon {frameSlot}\nshow ont run-info {ponPort} all`, description: "Просмотр состояния всех ONT ID на оптическом порту с указанием статуса" },
        { command: `show ont run-info all`, description: "Просмотр состояния всех ONT ID с указанием статуса" },
        { command: `config\ninterface gpon {frameSlot}\nshow port state all`, description: "Просмотр состояния всех оптических портов" },
        { command: `config\ninterface gpon {frameSlot}\nshow statistics ont {ponPort} {ontIdx}`, description: "Просмотр трафика на ONT ID" },
        { command: `config\ninterface gpon {frameSlot}\nshow statistics port {ponPort}`, description: "Просмотр трафика на оптическом порту" },
        { command: `config\ninterface gpon {frameSlot}\nshow statistics ont-line-quality {ponPort} {ontIdx}`, description: "Просмотр ошибок FEC/HEC на ONT ID" },
        { command: `show dhcp security-table`, description: "Просмотр получения IP-адресов для CPE" },
        { command: `show device`, description: "Просмотр информации о OLT" },
      ],
    },
  },

  // Уральский филиал (по умолчанию)
  eltex_ma4000: {
    label: "Eltex MA4000",
    services: {
      ims: ({ ontId, sn, ploam }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `description "ONT-${ontId}"`,
        sn ? `serial "${sn}"` : `! serial <SN>`,
        ploam ? `password "${ploam}"` : `! password <PLOAM>`,
        `service 4 profile cross-connect "crossconnect-01"`,
        `service 4 profile dba "dba-00"`,
        `profile ports "ports-01"`,
        `template "template-01"`,
        `exit`,
        `do commit`,
        `do confirm`,
      ].filter(Boolean),
      vims: ({ ontId, sn, ploam }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `description "ONT-${ontId}"`,
        sn ? `serial "${sn}"` : `! serial <SN>`,
        ploam ? `password "${ploam}"` : `! password <PLOAM>`,
        `service 4 profile cross-connect "crossconnect-01"`,
        `service 4 profile dba "dba-00"`,
        `profile ports "ports-01"`,
        `template "template-02"`,
        `exit`,
        `do commit`,
        `do confirm`,
      ].filter(Boolean),
    },
    diagnostics: {
      "Информация об ONT": [
        { command: `show interface ont {ontId} state`, description: "Статус ONT" },
      ],
      "Оптика": [
        { command: `show ont optical-info {ontId}`, description: "Оптические параметры" },
      ],
      "Конфигурация": [
        { command: `show running-config interface ont {ontId}`, description: "Конфигурация ONT" },
      ],
      "Конфигурация (подробно)": [
        { command: `show interface ont {ontId} configuration`, description: "Подробная конфигурация ONT" },
      ],
      "Состояние/сигнал": [
        { command: `show interface ont {ontId} ports`, description: "Состояние портов ONT" },
        { command: `show interface ont {ontId} connections`, description: "Причины разрывов/соединения" },
        { command: `show interface ont {ontId} laser`, description: "Оптический сигнал ONT" },
      ],
      "MAC-таблица": [
        { command: `show mac interface ont {ontId}`, description: "MAC-адреса на ONT" },
      ],
      "Профили": [
        { command: `show profile cross-connect`, description: "Список профилей cross-connect" },
        { command: `show profile dba`, description: "Список профилей dba" },
      ],
      "Алармы": [
        { command: `show ont alarms {ontId}`, description: "Алармы на ONT" },
      ],
    },
  },

  eltex_ltp: {
    label: "Eltex LTP",
    services: {
      ims: ({ ontId, sn, ploam }) => {
        const [slot = '1', port = '1'] = (ontId || '1/1').split('/');
        const desc = `ONT-0-${slot}-${port}`;
        return [
          `configure terminal`,
          `interface ont ${ontId}`,
          `description "${desc}"`,
          sn ? `serial "${sn}"` : `! serial <SN>`,
          ploam ? `password "${ploam}"` : `! password <PLOAM>`,
          `service 4 template "template-01"`,
          `enable`,
          `exit`,
          `do commit`,
        ].filter(Boolean);
      },
      vims: ({ ontId, sn, ploam }) => {
        const [slot = '1', port = '1'] = (ontId || '1/1').split('/');
        const desc = `ONT-0-${slot}-${port}`;
        return [
          `configure terminal`,
          `interface ont ${ontId}`,
          `description "${desc}"`,
          sn ? `serial "${sn}"` : `! serial <SN>`,
          ploam ? `password "${ploam}"` : `! password <PLOAM>`,
          `service 4 template "template-02"`,
          `enable`,
          `exit`,
          `do commit`,
        ].filter(Boolean);
      },
    },
    diagnostics: {
      "Информация об ONT": [
        { command: `show interface ont {ontId} state`, description: "Статус ONT" },
      ],
      "Оптика": [
        { command: `show interface ont {ontId} laser`, description: "Оптический сигнал ONT" },
      ],
      "Конфигурация": [
        { command: `show running-config interface ont {ontId}`, description: "Конфигурация ONT" },
      ],
      "Конфигурация (подробно)": [
        { command: `show interface ont {ontId} configuration`, description: "Подробная конфигурация ONT" },
      ],
      "Состояние/сигнал": [
        { command: `show interface ont {ontId} ports`, description: "Состояние портов ONT" },
        { command: `show interface ont {ontId} connections`, description: "Причины разрывов/соединения" },
      ],
      "MAC-таблица": [
        { command: `show mac interface ont {ontId}`, description: "MAC-адреса на ONT" },
      ],
    },
  },

  // Сибирские филиалы - Алтай (АФ)
  eltex_ma4000_af_csm: {
    label: "Алтай (АФ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `fec`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_af_esm: {
    label: "Алтай (АФ) - ESM (INT+IPTV)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `fec`,
        `service 0 profile cross-connect "crossconnect-02"`,
        `service 0 profile dba "dba_HSI"`,
        `service 2 profile cross-connect "crossconnect-04"`,
        `service 2 profile dba "dba_IPTV"`,
        `service 3 profile cross-connect "crossconnect-05"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "crossconnect-01"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Горный Алтай (гАФ) - 3 варианта
  eltex_ma4000_gaf_esm_v1: {
    label: "Горный Алтай (гАФ) - ESM Вариант 1",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `fec`,
        `service 0 profile cross-connect "crossconnect-02"`,
        `service 0 profile dba "dba_HSI"`,
        `service 3 profile cross-connect "crossconnect-05"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "crossconnect-00"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_gaf_esm_v2: {
    label: "Горный Алтай (гАФ) - ESM Вариант 2",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `fec`,
        `service 0 profile cross-connect "crossconnect-02"`,
        `service 0 profile dba "dba_HSI"`,
        `service 3 profile cross-connect "crossconnect-04"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "crossconnect-00"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_gaf_esm_v3: {
    label: "Горный Алтай (гАФ) - ESM Вариант 3",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `fec`,
        `service 0 profile cross-connect "crossconnect-02"`,
        `service 0 profile dba "dba_HSI"`,
        `service 3 profile cross-connect "crossconnect-05"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "crossconnect-01"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Новосибирский (НФ)
  eltex_ma4000_nsk_csm: {
    label: "Новосибирский (НФ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_nsk_esm_ipiptv: {
    label: "Новосибирский (НФ) - ESM (INT+IPTV+SIP)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 4 profile cross-connect "crossconnect-00"`,
        `service 4 profile dba "dba-00"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `template "template-01"`,
        `rf-port-state "enabled"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_nsk_esm: {
    label: "Новосибирский (НФ) - ESM (INT+IPTV)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "crossconnect-01"`,
        `service 0 profile dba "dba_HSI"`,
        `service 3 profile cross-connect "crossconnect-04"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "crossconnect-00"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ltp_nsk_esm: {
    label: "Новосибирский (НФ) - ESM (LTP8-16N)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `no multicast-filter`,
        `profile management "management-IOP"`,
        `profile ports "ESM"`,
        `service 1 profile cross-connect "TR_069" dba "dba_TR-069"`,
        `service 2 profile cross-connect "HSI_ESM" dba "HSI"`,
        `service 3 profile cross-connect "IP-TV_ESM" dba "IPTV"`,
        `service 4 profile cross-connect "VoIP_ESM" dba "VoIP"`,
        `fec`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ltp_nsk_csm: {
    label: "Новосибирский (НФ) - CSM (LTP8-16N)",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `profile management "management-IOP"`,
        `profile ports "CSM"`,
        `service 1 profile cross-connect "TR_069" dba "dba_TR-069"`,
        `service 2 custom inner vid ${cvid}`,
        `service 2 custom outer vid ${svid}`,
        `service 2 profile cross-connect "CSM" dba "HSI"`,
        `fec`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_nsk_ntu1: {
    label: "Новосибирский (НФ) - NTU-1",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `template "NTU-1-3Play"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_nsk_eos: {
    label: "Новосибирский (НФ) - Бывший Оператор ЕОС",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `serial "${sn}"`,
        `fec`,
        `no broadcast-downstream filter`,
        `template "RG-3Play"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Кемеровский (КемФ)
  eltex_ma4000_kem_csm: {
    label: "Кемеровский (КемФ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_kem_esm: {
    label: "Кемеровский (КемФ) - ESM (INT+IPTV+SIP)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI"`,
        `service 0 profile dba "dba_HSI"`,
        `service 1 profile cross-connect "VOIP"`,
        `service 1 profile dba "dba_VOIP"`,
        `service 3 profile cross-connect "IPTV"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Омский (ОФ)
  eltex_ma4000_omsk_csm: {
    label: "Омский (ОФ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_omsk_esm: {
    label: "Омский (ОФ) - ESM (INT+IPTV)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI"`,
        `service 0 profile dba "dba_HSI"`,
        `service 3 profile cross-connect "IPTV"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Томский (ТФ)
  eltex_ma4000_tomsk_csm: {
    label: "Томский (ТФ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_tomsk_esm: {
    label: "Томский (ТФ) - ESM (INT+IPTV)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI"`,
        `service 0 profile dba "dba_HSI"`,
        `service 3 profile cross-connect "IPTV"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Бурятия (БФЛ)
  eltex_ma4000_buryatia_csm: {
    label: "Бурятия (БФЛ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_buryatia_esm: {
    label: "Бурятия (БФЛ) - ESM (INT+SIP+IPTV)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI"`,
        `service 0 profile dba "dba_HSI"`,
        `service 1 profile cross-connect "VOIP"`,
        `service 1 profile dba "dba_VOIP"`,
        `service 3 profile cross-connect "IPTV"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Забайкалье (ЗабФ)
  eltex_ma4000_zab_csm: {
    label: "Забайкалье (ЗабФ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_zab_esm: {
    label: "Забайкалье (ЗабФ) - ESM (INT+IPTV)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI"`,
        `service 0 profile dba "dba_HSI"`,
        `service 3 profile cross-connect "IPTV"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Иркутский (ИФ)
  eltex_ma4000_irk_csm: {
    label: "Иркутский (ИФ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_irk_esm: {
    label: "Иркутский (ИФ) - ESM (INT+IPTV)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI"`,
        `service 0 profile dba "dba_HSI"`,
        `service 3 profile cross-connect "IPTV"`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "ports-IOP"`,
        `profile management "management-IOP"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },

  // Красноярский (КрФ)
  eltex_ma4000_kras_csm: {
    label: "Красноярский (КрФ) - CSM",
    type: "csm",
    services: {
      default: ({ ontId, sn, cvid, svid }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI-CSM"`,
        `service 0 profile dba "dba_HSI"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports "CSM"`,
        `profile management "management-IOP"`,
        `service 0 custom cvid ${cvid}`,
        `service 0 custom svid ${svid}`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_kras_esm: {
    label: "Красноярский (КрФ) - ESM (INT+IPTV+SIP)",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect HSI`,
        `service 0 profile dba dba_HSI`,
        `service 2 profile cross-connect VOIP`,
        `service 2 profile dba "dba_VOIP"`,
        `service 3 profile cross-connect IPTV`,
        `service 3 profile dba "dba_IPTV"`,
        `service 4 profile cross-connect TR-069`,
        `service 4 profile dba "dba_TR-069"`,
        `profile ports ports-IOP`,
        `profile management management-IOP`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
  eltex_ma4000_kras_hak_esm: {
    label: "Красноярский (КрФ) - ESM (INT+IPTV) Хакасия",
    services: {
      default: ({ ontId, sn }) => [
        `configure terminal`,
        `interface ont ${ontId}`,
        `fec`,
        `serial "${sn}"`,
        `service 0 profile cross-connect "HSI"`,
        `service 0 profile dba "dba-00"`,
        `service 3 profile cross-connect "IPTV"`,
        `service 3 profile dba "dba-00"`,
        `service 4 profile cross-connect "TR-069"`,
        `service 4 profile dba "dba-00"`,
        `profile ports "RG"`,
        `profile management "Axiros"`,
        `template "template-00"`,
        `do commit`,
        `do confirm`,
        `exit`,
        `exit`,
        `commit`,
        `confirm`,
      ].filter(Boolean),
    },
  },
};

// Диагностика для Сибирских филиалов:
// - все MA4000-конфиги используют диагностику MA4000 (Урал)
// - LTP-конфиги используют диагностику LTP (Урал)
const uralMa4000Diag = window.gponDevices.eltex_ma4000?.diagnostics || {};
const uralLtpDiag = window.gponDevices.eltex_ltp?.diagnostics || {};

Object.keys(window.gponDevices).forEach((key) => {
  if (!key.startsWith('eltex_')) return;
  if (window.gponDevices[key].diagnostics) return;
  window.gponDevices[key].diagnostics = key.startsWith('eltex_ltp_')
    ? uralLtpDiag
    : uralMa4000Diag;
});
